= acrobat
Dominic Sisneros <https://github.com/dsisnero[@dsisnero]
//settings
:page-layout: base
:idprefix:
:idseparator: -
:source-language: ruby
:language: {source-language}
// Uris
:uri-org: https://github.com/dsisnero
:uri-repo: {uri-org}/acrobat
:uri-issues: {uri-repo}/issues
:uri-contributors: {uri-repo}/graphs/contributors
:uri-changelog: {uri-rel-file-base}CHANGELOG.adoc
:uri-rel-file-base: {uri-repo}/blob/master/
:uri-rel-tree-base: {uri-repo}/tree/master/
:uri-contribute: {uri-rel-file-base}CONTRIBUTING.adoc
:uri-license: {uri-rel-file-base}LICENSE.adoc

== DESCRIPTION:

The acrobat gem is a library that uses WIN32OLE to automate pdf functions.  Adobe Reader or Adobe Acrobat must be installed and then you can fill forms and merge documents

== Requirements

* Windows Adobe Acrobat installed

== Install 0ptions

acrobat  can be installed using (a) the `gem install` command, (b) Bundler

=== (a) gem install

Open a terminal and type
$ gem install acrobat

.Upgrading your installation
[TIP]
====
If you have an earlier version of acrobat installed you can update it using:

$ gem update acrobat

If you install a new version of the gem using `gem install` instead of
gem update, you'll have multiple versions installed. If that's the
case, use the following gem command to remove the old versions:

$ gem cleanup acrobat
====
=== (b) Bundler

. Create a Gemfile in the root folder of your project (or the current directory)
. Add the `asciidoctor` gem to your Gemfile as follows:
+
[source]
----
source 'https://rubygems.org'
gem 'acrobat'
# or specify the version explicitly
# gem 'acrobat', '0.0.5'
----

. Save the Gemfile
. Open a terminal and install the gem using:

 $ bundle

To upgrade the gem, specify the new version in the Gemfile and run `bundle` again.
Using `bundle update` is *not* recommended as it will also update other gems, which may not be the desired result.

== Usage

[source,ruby]
====

  require 'acrobat'
  Adobe::Acrobat.run do |app|
    fields = {city: 'City', state: 'State', zip: 'zip'}
    doc = app.open('apd_document.pdf')
    doc.fill_form(fields)
    doc.show
    doc2 = app.open('another_doc.pdf')
    doc2.fill_form(fields)
    doc1.merge_doc(doc2)
    doc1.save_as(name: 'merged_doc.pdf', dir: 'tmp')
  end
    
    

====

== Getting Help


We encourage you to ask questions and discuss any aspects of the project on the discussion list, Twitter or IRC.

Mailing list:: {uri-discuss}


ifdef::env-github[]
Further information and documentation about acrobat gem can be found on the project's website.

{uri-project}/[Home] | {uri-news}[News] | {uri-docs}[Docs]
endif::[]

The project's source code, issue tracker, and sub-projects are on github

Source repository (git):: {uri-repo}
Issue tracker:: {uri-issues}
acrobat organization on GitHub:: {uri-org}

== Copyright and Licensing

Copyright (C) 2012-2016 Dominic Sisneros and the acrobat-Ruby Project.
Free use of this software is granted under the terms of the MIT License.

See the {uri-license}[LICENSE] file for details.
